name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      # We support Node Current, LTS, and Maintenance. See
      # https://nodejs.org/en/about/releases/ for release schedule.
      #
      # We test all supported Node versions on Linux, and the oldest and newest
      # on macOS/Windows.
      matrix:
        include:
          - node: 16
            os: ubuntu-22.04
          - node: 16
            os: macos-12
          - node: 16
            os: windows-2022
          - node: 18
            os: ubuntu-22.04
          - node: 19
            os: ubuntu-22.04
          - node: 19
            os: macos-12
          - node: 19
            os: windows-2022
          - node: 20
            os: ubuntu-22.04
          - node: 20
            os: macos-12
          - node: 20
            os: windows-2022

      # Allow all matrix configurations to complete, instead of cancelling as
      # soon as one fails. Useful because we often have different kinds of
      # failures depending on the OS.
      fail-fast: false

    # Sometimes windows is far slower than the other OSs. Give it enough
    # time to complete if it's going to.
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}

    env:
      # TODO(aomarks) It's a little difficult to read the test results, because
      # stdio streams of all parallel processes are interleaved. Remove this
      # after implementing stdio locking.
      WIREIT_PARALLEL: 1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - uses: google/wireit@setup-github-actions-caching/v1

      - run: npm ci

      # See https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions for why we need xvfb-run
      - run: npm test
        if: runner.os != 'Linux'
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

  lint-and-format:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
