name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      # We support Node Latest, Active LTS, and the most recent Maintenance LTS.
      # See https://nodejs.org/en/about/releases/ for Node release schedule.
      matrix:
        version: [14, 16, 18]
        os: [ubuntu-20.04, macos-11, windows-2022]

      # Allow all matrix configurations to complete, instead of cancelling as
      # soon as one fails. Useful because we often have different kinds of
      # failures depending on the OS.
      fail-fast: false

    # Sometimes windows is far slower than the other OSs. Give it enough
    # time to complete if it's going to.
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}

    env:
      # TODO(aomarks) It's a little difficult to read the test results, because
      # stdio streams of all parallel processes are interleaved. Remove this
      # after implementing stdio locking.
      WIREIT_PARALLEL: 1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - uses: google/wireit@setup-github-actions-caching/v1

      - run: node --version; npm --version

      - run: npm ci

      # Don't bother running the vscode-extension tests on Node 14, because the
      # minimum version of VSCode we support uses Node 16.
      - if: matrix.node == 14
        run: npm run test:headless

      # See https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions for why we need xvfb-run
      - run: npm test
        if: runner.os != 'Linux' && matrix.node != 14
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux' && matrix.node != 14

  lint-and-format:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
